CODING TEMPLE CAPSTONE II - IHME: USA Health Care Spending by Payer 1996-2016 
- Shanjali Arul, June 2024

Step 1: Data Collection 

Dataset:IHME: USA Health Care Spending by Payer 1996-2016

https://www.kaggle.com/datasets/adarshsng/usa-health-care-spending-19962016

The Disease Expenditure Project (DEX) at IHME produced estimates for US spending on health care according to 3 types of payers (public insurance [including Medicare, Medicaid, and other government programs], private insurance, or out-of-pocket payments) and by health condition, age group, sex, and type of care for 1996 through 2016. 

Types of care include ambulatory care, inpatient care, nursing care facility stay, emergency department care, dental care, prescribed pharmaceutical care, and government administration and net cost of insurance programs.

- Government budgets, insurance claims, facility records, household surveys, and official US records from 1996 through 2016 were used to produce the results. 
- Spending estimates were produced for 154 conditons, which were aggregated into 14 health categories. 
- This dataset contains estimates for the aggregate health categories.

Format: 1 csv file, tabular 

Defining Question: “How does the cost of healthcare vary across different types of care? 

Hypothesis: “Healthcare spending in the USA has been increasing over the years”.

The Data file
Year_id : YearTime period of estimate.
age_group_ID : Age Group
IDUnique : numeric identifier for the age group generated and stored in an IHME database of data dimensions
age_group_name : Age Group NameAge group estimated
sex_ID : Sex IDUnique numeric identifier for the sex generated and stored in an IHME database of data dimensions
sex : SexGender for the estimate
function functionUnique identifier for the types of care
type_of_care : Types ofcareTypes of care estimated
acause : acauseUnique identifier for the cause
Cause_name : Cause nameCause for the estimate
Cause_id : Cause IDUnique numeric identifier for the cause
select all columns to view these !!
Mean_all : Meanall payersMean estimatefor all payers
Lower_all : 95% uncertainty interval (lower bound)2.5% percentile estimatefor all payers
Upper_all : 95% uncertainty interval (upper bound)97.5% percentile estimatefor all payers
Mean_pub : Meanpublic insuranceMean estimatefor public insurance
Lower_pub : 95% uncertainty interval (lower bound)2.5% percentile estimatefor public insurance
Upper_pub : 95% uncertainty interval (upper bound)97.5% percentile estimatefor public insurance
Mean_pri : Meanprivate insuranceMean estimatefor private insurance
Lower_pri : 95% uncertainty interval (lower bound)2.5% percentile estimatefor private insurance
Upper_pri : 95% uncertainty interval (upper bound)97.5% percentile estimatefor private insurance
Mean_oop : Meanout-of-pocketMean estimatefor out-of-pocket
Lower_oop : 95% uncertainty interval (lower bound)2.5% percentile estimatefor out-of-pocket
Upper_oop : 95% uncertainty interval (upper bound)97.5% percentile estimatefor out-of-pocket
year_id
YearTime period of estimate.

age_group_id
Age Group

age_group_name
Age Group

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv

df = pd.read_csv('IHME.csv')

# This will display the first 5 rows of the DataFrame
print(df.head())

print(df.describe())

IHME = pd.read_csv("IHME.csv")
IHME

   year_id  age_group_id age_group_name  sex_id   sex function  \
0     1996             5         1 to 4       1  Male       AM
1     1997             5         1 to 4       1  Male       AM
2     1998             5         1 to 4       1  Male       AM
3     1999             5         1 to 4       1  Male       AM
4     2000             5         1 to 4       1  Male       AM

      type_of_care acause                                         cause_name  \
0  Ambulatory care  _comm  Communicable, maternal, neonatal, and nutritio...
1  Ambulatory care  _comm  Communicable, maternal, neonatal, and nutritio...
2  Ambulatory care  _comm  Communicable, maternal, neonatal, and nutritio...
3  Ambulatory care  _comm  Communicable, maternal, neonatal, and nutritio...
4  Ambulatory care  _comm  Communicable, maternal, neonatal, and nutritio...

   cause_id  ...    upper_all    mean_pub   lower_pub   upper_pub  \
0     295.0  ...  3124.714039  605.080639  437.147993  778.997570
1     295.0  ...  2863.786701  577.071155  433.332288  714.763493
2     295.0  ...  2761.832455  554.274639  446.150240  657.940286
3     295.0  ...  2643.992850  548.143397  460.727384  649.451470
4     295.0  ...  2626.366456  558.334833  471.963383  648.870566

      mean_pri    lower_pri    upper_pri    mean_oop   lower_oop   upper_oop
0  1650.995720  1296.810196  2060.739834  319.415442  240.206345  410.541398
1  1582.869154  1358.734096  1877.624893  314.644096  258.494447  377.892018
2  1580.121390  1399.807654  1821.051369  311.822065  273.061851  357.326710
3  1544.026671  1362.885139  1737.044092  303.040544  263.238698  341.052978
4  1528.086866  1341.050495  1704.843819  296.488956  253.989528  331.852288

[5 rows x 22 columns]
             year_id   age_group_id         sex_id      cause_id  \
count  106113.000000  106113.000000  106113.000000  90006.000000
mean     2006.000000      21.975064       1.982980    534.007466
std         6.055329      32.686663       0.812841    100.977681
min      1996.000000       5.000000       1.000000    295.000000
25%      2001.000000       9.000000       1.000000    508.000000
50%      2006.000000      14.000000       2.000000    542.000000
75%      2011.000000      19.000000       3.000000    626.000000
max      2016.000000     160.000000       3.000000    687.000000

            mean_all      lower_all      upper_all       mean_pub  \
count  106113.000000  106113.000000  106113.000000  106113.000000
mean     1163.380515    1042.512647    1299.268043     462.078653
std      3455.484197    3190.184639    3760.374048    1564.636980
min         0.001822       0.000000       0.004284       0.001266
25%        54.680116      39.711669      72.705949      16.090358
50%       292.626280     248.442679     345.561604      83.285456
75%       983.998914     859.899927    1124.454844     301.666103
max    119955.015000  105380.626600  135624.002600   43531.436770

           lower_pub      upper_pub       mean_pri      lower_pri  \
count  106113.000000  106113.000000  106113.000000  106113.000000
mean      392.809043     540.339390     569.044060     477.736526
std      1406.920581    1741.470016    1773.768585    1562.413927
min         0.000000       0.003815       0.000225       0.000000
25%         9.663719      23.720963      12.915284       6.721484
50%        58.647070     111.853413     113.433104      82.666411
75%       237.803641     372.655462     442.063395     348.911354
max     41305.538620   51645.601290   67011.208150   57334.407980

           upper_pri       mean_oop      lower_oop      upper_oop
count  106113.000000  106113.000000  106113.000000  106113.000000
mean      669.734054     132.257802     106.136566     165.379118
std      2009.999398     557.088333     474.949588     665.173662
min         0.000400       0.000000       0.000000       0.000000
25%        21.581451       0.312624       0.044677       0.817752
50%       151.064424      11.967518       7.135920      18.860587
75%       542.152534      82.905484      61.011464     112.864391
max     76487.281200   16921.731080   16198.015480   23526.613830

,year_id,age_group_id,age_group_name,sex_id,sex,function,type_of_care,acause,cause_name,cause_id,...,upper_all,mean_pub,lower_pub,upper_pub,mean_pri,lower_pri,upper_pri,mean_oop,lower_oop,upper_oop
0,1996,5,1 to 4,1,Male,AM,Ambulatory care,_comm,"Communicable, maternal, neonatal, and nutritio...",295.0,...,3124.714039,605.080639,437.147993,778.997570,1650.995720,1296.810196,2060.739834,319.415442,240.206345,410.541398
1,1997,5,1 to 4,1,Male,AM,Ambulatory care,_comm,"Communicable, maternal, neonatal, and nutritio...",295.0,...,2863.786701,577.071155,433.332288,714.763493,1582.869154,1358.734096,1877.624893,314.644096,258.494447,377.892018
2,1998,5,1 to 4,1,Male,AM,Ambulatory care,_comm,"Communicable, maternal, neonatal, and nutritio...",295.0,...,2761.832455,554.274639,446.150240,657.940286,1580.121390,1399.807654,1821.051369,311.822065,273.061851,357.326710
3,1999,5,1 to 4,1,Male,AM,Ambulatory care,_comm,"Communicable, maternal, neonatal, and nutritio...",295.0,...,2643.992850,548.143397,460.727384,649.451470,1544.026671,1362.885139,1737.044092,303.040544,263.238698,341.052978
4,2000,5,1 to 4,1,Male,AM,Ambulatory care,_comm,"Communicable, maternal, neonatal, and nutritio...",295.0,...,2626.366456,558.334833,471.963383,648.870566,1528.086866,1341.050495,1704.843819,296.488956,253.989528,331.852288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106108,2012,160,85 plus,3,Both,GA,Government Administration and Net Cost of Insu...,rf,Expenditure on risk factors,NaN,...,828.709154,517.397028,474.367045,606.207718,210.958020,170.513282,268.883452,0.000000,0.000000,0.000000
106109,2013,160,85 plus,3,Both,GA,Government Administration and Net Cost of Insu...,rf,Expenditure on risk factors,NaN,...,860.117431,533.449534,483.324079,642.292570,202.358454,159.388043,266.593891,0.000000,0.000000,0.000000
106110,2014,160,85 plus,3,Both,GA,Government Administration and Net Cost of Insu...,rf,Expenditure on risk factors,NaN,...,963.345003,591.105164,523.721376,736.991358,207.667645,158.846920,283.573512,0.000000,0.000000,0.000000
106111,2015,160,85 plus,3,Both,GA,Government Administration and Net Cost of Insu...,rf,Expenditure on risk factors,NaN,...,1035.478437,622.077646,538.850912,808.184147,200.802177,148.172534,284.307593,0.000000,0.000000,0.000000
106112,2016,160,85 plus,3,Both,GA,Government Administration and Net Cost of Insu...,rf,Expenditure on risk factors,NaN,...,1109.542453,642.363960,539.184185,873.419019,206.110038,144.702723,303.076566,0.000000,0.000000,0.000000